--FUNCIONES PREDEFINIDAS DE HASKELL
--DEVUELVE EL VALOR ABSOLUTO DE X
abs x
--MENOR ENTERO NO MENOR QUE X
ceiling x
--DEVUELVE EL VALOR SIGUIENTE DE LA X
succ x
--OBTIENE EL MENOR
min x y 
--OBTIENE EL MAYOR
max x y
--DIVIDE X ENTRE Y
div x y
--OBTIENE EL MODULO DE X Y
mod x y
--VERIFICA SI X ES PAR
even x
--NUMERO MAYOR ENTERO NO MAYOR QUE X
floor x
--MAXIMO COMUN DIVISOR
gcd x y
--NEGACION DE BOOLEANA
not x
--VERIFICA SI ES NUMERO PAR
odd x
--DEVUELVE 1 SI ES POSITIVO, -1 SI ES NEGATIVO
signum x
--RETORNA EL SEGUNDO ELEMENTO Y
snd (x,y)